# Site settings
title: Unbounce
subtitle: open-sourced
email: opensource@unbounce.com
description: ""
baseurl: ""
url: "http://unbounce.com"
username: unbounce

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: :compressed
